#!/usr/bin/env python3
# gen_layers.py — generates include/gen_layers.h: 3 placeholder parallax layers
# as 8-bit indexed images + RGB565 palettes, stored const (flash) on ESP32.
# Placeholder art only — replaced by real chunk tiles at M3.
# Regenerate: python3 tools/gen_layers.py > include/gen_layers.h
import math, sys

W, H = 512, 272
TRANS = 0  # palette index 0 = transparent for keyed layers

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

class LCG:
    def __init__(self, seed): self.s = seed
    def next(self):
        self.s = (self.s * 1664525 + 1013904223) & 0xFFFFFFFF
        return self.s
    def range(self, lo, hi): return lo + self.next() % (hi - lo + 1)

class Layer:
    def __init__(self, name):
        self.name = name
        self.px = [[0] * W for _ in range(H)]
        self.pal = [0x0000]          # index 0 reserved (transparent / black)
        self.lut = {None: 0}
    def color(self, c):
        if c not in self.lut:
            self.pal.append(c)
            assert len(self.pal) <= 256, "palette overflow"
            self.lut[c] = len(self.pal) - 1
        return self.lut[c]
    def hline(self, x0, x1, y, ci):
        if y < 0 or y >= H: return
        x0, x1 = max(0, x0), min(W - 1, x1)
        row = self.px[y]
        for x in range(x0, x1 + 1): row[x] = ci
    def fill_circle(self, cx, cy, r, ci):
        for dy in range(-r, r + 1):
            hw = int(math.isqrt(r * r - dy * dy))
            self.hline(cx - hw, cx + hw, cy + dy, ci)
    def spike_down(self, x, w, h, ci):     # hangs from y=0
        for y in range(h):
            hw = int((w / 2) * (1 - y / h))
            self.hline(x + w // 2 - hw, x + w // 2 + hw, y, ci)
    def spike_up(self, x, w, h, base_y, ci):  # rises from base_y
        for i in range(h):
            hw = int((w / 2) * (1 - i / h))
            self.hline(x + w // 2 - hw, x + w // 2 + hw, base_y - i, ci)

rng = LCG(0xC0FFEE)

far = Layer("far")
for y in range(H):                          # dark vertical gradient
    v = 20 + (y * 30) // H
    ci = far.color(rgb565(v // 2, v // 2, v))
    far.hline(0, W - 1, y, ci)
blob = far.color(rgb565(18, 18, 30))
for _ in range(40):
    far.fill_circle(rng.range(0, W - 1), rng.range(0, H - 1), rng.range(4, 18), blob)

mid = Layer("mid")
rock = mid.color(rgb565(45, 40, 55))
for _ in range(12):
    x, w = rng.range(0, W - 40), rng.range(20, 40)
    mid.spike_down(x, w, rng.range(20, 90), rock)
    mid.spike_up(x, w, rng.range(20, 90), H - 1, rock)

near = Layer("near")
floor_c = near.color(rgb565(80, 65, 50))
stal_c  = near.color(rgb565(95, 78, 60))
floor_y = H - 40
for y in range(floor_y, H):
    near.hline(0, W - 1, y, floor_c)
for _ in range(8):
    x, w = rng.range(0, W - 30), rng.range(14, 30)
    near.spike_up(x, w, rng.range(15, 45), floor_y - 1, stal_c)

def emit(layer, out):
    # Per-row content flag: 1 if any non-transparent pixel in that row.
    # Lets the compositor skip keyed passes over fully-empty rows.
    flags = [1 if any(v != 0 for v in layer.px[y]) else 0 for y in range(H)]
    out.write(f"static const uint8_t {layer.name}_rowflag[{H}] = {{")
    out.write(",".join(str(f) for f in flags))
    out.write("};\n")
    out.write(f"static const uint16_t {layer.name}_pal[{len(layer.pal)}] = {{")
    out.write(",".join(str(c) for c in layer.pal))
    out.write("};\n")
    out.write(f"static const uint8_t {layer.name}_px[{H}*{W}] = {{\n")
    for y in range(H):
        out.write(",".join(str(v) for v in layer.px[y]))
        out.write(",\n" if y < H - 1 else "\n")
    out.write("};\n\n")

out = sys.stdout
out.write("// gen_layers.h — GENERATED by tools/gen_layers.py. Do not hand-edit.\n")
out.write("// 3 placeholder parallax layers, 8-bit indexed + RGB565 palette, flash-resident.\n")
out.write("// Index 0 = transparent on keyed layers (mid/near).\n")
out.write("#pragma once\n#include <stdint.h>\n\n")
out.write(f"#define GEN_LAYER_W {W}\n#define GEN_LAYER_H {H}\n\n")
for L in (far, mid, near):
    emit(L, out)
